services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: shreddeded_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db-migration/liquibase/changelogs:/liquibase/changelog
      - ./db-migration/liquibase/drivers:/liquibase/drivers
    command:
      [
        "--url=jdbc:postgresql://db:5432/${POSTGRES_DB}",
        "--changeLogFile=db.changelog-master.xml",
        "--username=${POSTGRES_USER}",
        "--password=${POSTGRES_PASSWORD}",
        "--classpath=/liquibase/drivers/postgresql-42.7.10.jar",
        "update"
      ]
    env_file:
      - .env

volumes:
  db_data:

networks:
  default:
    name: shreddeded_network
